using System.Linq;
using Content.Shared._Forge.Payroll;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Payroll.UI;

[GenerateTypedNameReferences]
public sealed partial class ForgePayrollConsoleWindow : DefaultWindow
{
    public event Action<NetEntity>? OnRecordSelected;
    public event Action<NetEntity, string, int, int, ForgePayrollEmploymentStatus>? OnSavePressed;
    public event Action<NetEntity>? OnPayNowPressed;
    public event Action<NetEntity, int, string>? OnFinePressed;

    private bool _isPopulating;
    private NetEntity? _selected;
    private NetEntity? _lastPopulatedRecord;
    private string? _lastJobPrototype;
    private ForgePayrollEmploymentStatus? _lastStatus;
    private int? _lastBaseSalary;
    private int? _lastAdjustment;
    private readonly List<string> _jobOptionIds = new();
    private readonly Dictionary<string, ForgePayrollJobOptionState> _jobOptions = new();

    public ForgePayrollConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        RecordsList.OnItemSelected += args =>
        {
            if (_isPopulating || RecordsList[args.ItemIndex].Metadata is not NetEntity employee)
                return;

            _selected = employee;
            OnRecordSelected?.Invoke(employee);
        };

        RecordsList.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                _selected = null;
        };

        BaseSalarySpinBox.IsValid = value => value is >= 0 and <= 250000;
        AdjustmentSpinBox.IsValid = value => value is >= -250000 and <= 250000;
        FineAmountSpinBox.IsValid = value => value is >= 1 and <= 250000;
        FineReasonLineEdit.IsValid = value => value.Length <= 96;

        foreach (var status in Enum.GetValues<ForgePayrollEmploymentStatus>())
        {
            StatusOptionButton.AddItem(GetStatusName(status), (int) status);
        }

        StatusOptionButton.OnItemSelected += args => StatusOptionButton.SelectId(args.Id);
        JobOptionButton.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            ApplySelectedJobOption();
        };

        BaseSalarySpinBox.ValueChanged += _ => UpdateTotalLabel();
        AdjustmentSpinBox.ValueChanged += _ => UpdateTotalLabel();

        SaveButton.OnPressed += _ =>
        {
            if (_selected is not { } employee)
                return;

            OnSavePressed?.Invoke(
                employee,
                GetSelectedJobPrototype(),
                BaseSalarySpinBox.Value,
                AdjustmentSpinBox.Value,
                (ForgePayrollEmploymentStatus) StatusOptionButton.SelectedId);
        };

        PayNowButton.OnPressed += _ =>
        {
            if (_selected is { } employee)
                OnPayNowPressed?.Invoke(employee);
        };

        FineButton.OnPressed += _ =>
        {
            if (_selected is { } employee)
                OnFinePressed?.Invoke(employee, FineAmountSpinBox.Value, FineReasonLineEdit.Text);
        };
    }

    public void UpdateState(ForgePayrollConsoleState state)
    {
        var selectedRecord = _selected is { } selected
            ? state.Records.FirstOrDefault(record => record.Entity == selected)
            : null;

        if (selectedRecord == null && state.Selected is { } stateSelected)
        {
            selectedRecord = state.Records.FirstOrDefault(record => record.Entity == stateSelected);
            _selected = stateSelected;
        }
        else if (selectedRecord == null)
        {
            _selected = null;
        }

        PopulateJobOptions(state.JobOptions);
        PopulateRecords(state);
        PopulateEditor(selectedRecord, state.CanEdit);
    }

    private void PopulateJobOptions(IReadOnlyList<ForgePayrollJobOptionState> jobOptions)
    {
        var selectedJob = GetSelectedJobPrototype();

        _isPopulating = true;
        JobOptionButton.Clear();
        _jobOptionIds.Clear();
        _jobOptions.Clear();

        foreach (var option in jobOptions)
        {
            var id = _jobOptionIds.Count;
            _jobOptionIds.Add(option.JobPrototype);
            _jobOptions[option.JobPrototype] = option;
            JobOptionButton.AddItem(Loc.GetString("forge-payroll-console-job-option",
                ("job", option.JobTitle),
                ("department", option.Department)), id);
        }

        if (!string.IsNullOrWhiteSpace(selectedJob))
            TrySelectJob(selectedJob);

        _isPopulating = false;
    }

    private void PopulateRecords(ForgePayrollConsoleState state)
    {
        _isPopulating = true;
        RecordsList.Clear();
        RecordsList.ClearSelected();
        CrewCountLabel.Text = Loc.GetString("forge-payroll-console-crew-count", ("count", state.Records.Count));

        foreach (var record in state.Records)
        {
            var item = RecordsList.AddItem(Loc.GetString("forge-payroll-console-record-entry",
                ("name", record.EmployeeName),
                ("job", record.JobTitle),
                ("salary", record.TotalSalary),
                ("status", GetStatusName(record.Status))));
            item.Metadata = record.Entity;
            item.Selected = record.Entity == _selected;
        }

        _isPopulating = false;
    }

    private void PopulateEditor(ForgePayrollRecordState? record, bool canEdit)
    {
        var hasRecord = record != null;
        var selectedChanged = record?.Entity != _lastPopulatedRecord;

        SelectionLabel.Text = hasRecord
            ? Loc.GetString("forge-payroll-console-selected")
            : Loc.GetString("forge-payroll-console-no-selection");

        EmployeeNameLabel.Text = record?.EmployeeName ?? string.Empty;

        if (record == null)
        {
            JobPrototypeLabel.Text = string.Empty;
            DepartmentLabel.Text = string.Empty;
            JobOptionButton.TrySelect(0);
            StatusOptionButton.TrySelectId((int) ForgePayrollEmploymentStatus.Working);
            BaseSalarySpinBox.OverrideValue(0);
            AdjustmentSpinBox.OverrideValue(0);
            FineAmountSpinBox.OverrideValue(1);
            FineReasonLineEdit.Text = string.Empty;
            ClearEditorTracking();
        }
        else
        {
            var jobDirty = _lastJobPrototype != null && GetSelectedJobPrototype() != _lastJobPrototype;
            var statusDirty = _lastStatus != null && StatusOptionButton.SelectedId != (int) _lastStatus.Value;
            var baseSalaryDirty = _lastBaseSalary != null && BaseSalarySpinBox.Value != _lastBaseSalary.Value;
            var adjustmentDirty = _lastAdjustment != null && AdjustmentSpinBox.Value != _lastAdjustment.Value;

            if (selectedChanged || !jobDirty)
                TrySelectJob(record.JobPrototype);

            if (selectedChanged || !statusDirty)
                StatusOptionButton.TrySelectId((int) record.Status);

            if (selectedChanged || !baseSalaryDirty)
                BaseSalarySpinBox.OverrideValue(record.BaseSalary);

            if (selectedChanged || !adjustmentDirty)
                AdjustmentSpinBox.OverrideValue(record.Adjustment);

            if (selectedChanged)
            {
                FineAmountSpinBox.OverrideValue(100);
                FineReasonLineEdit.Text = string.Empty;
            }

            _lastPopulatedRecord = record.Entity;
            _lastJobPrototype = record.JobPrototype;
            _lastStatus = record.Status;
            _lastBaseSalary = record.BaseSalary;
            _lastAdjustment = record.Adjustment;

            if (!jobDirty)
            {
                JobPrototypeLabel.Text = record.JobPrototype;
                DepartmentLabel.Text = record.Department;
            }
            else
            {
                ApplySelectedJobOption(false);
            }
        }

        NextPayLabel.Text = record == null
            ? string.Empty
            : FormatDuration(record.SecondsToNextPay);
        LastPayLabel.Text = record == null
            ? string.Empty
            : Loc.GetString("forge-payroll-console-last-pay-value", ("amount", record.LastPaidAmount));
        var fineReason = record == null || string.IsNullOrWhiteSpace(record.LastFineReason)
            ? Loc.GetString("forge-payroll-console-fine-no-reason")
            : record.LastFineReason;
        LastFineLabel.Text = record == null || record.LastFineAmount <= 0
            ? Loc.GetString("forge-payroll-console-no-fine")
            : Loc.GetString("forge-payroll-console-last-fine-value",
                ("amount", record.LastFineAmount),
                ("reason", fineReason));
        OutstandingFineLabel.Text = record == null
            ? string.Empty
            : Loc.GetString("forge-payroll-console-total-value", ("amount", record.OutstandingFineAmount));

        JobOptionButton.Disabled = !hasRecord || !canEdit || JobOptionButton.ItemCount <= 0;
        StatusOptionButton.Disabled = !hasRecord || !canEdit;
        BaseSalarySpinBox.LineEditDisabled = !hasRecord || !canEdit;
        BaseSalarySpinBox.SetButtonDisabled(!hasRecord || !canEdit);
        AdjustmentSpinBox.LineEditDisabled = !hasRecord || !canEdit;
        AdjustmentSpinBox.SetButtonDisabled(!hasRecord || !canEdit);
        FineAmountSpinBox.LineEditDisabled = !hasRecord || !canEdit;
        FineAmountSpinBox.SetButtonDisabled(!hasRecord || !canEdit);
        FineReasonLineEdit.Editable = hasRecord && canEdit;
        SaveButton.Disabled = !hasRecord || !canEdit;
        FineButton.Disabled = !hasRecord || !canEdit;
        PayNowButton.Disabled = !hasRecord || !canEdit || record?.TotalSalary <= 0 ||
                                record?.Status != ForgePayrollEmploymentStatus.Working;

        UpdateTotalLabel();
    }

    private void ApplySelectedJobOption(bool updateBaseSalary = true)
    {
        if (_isPopulating || !_jobOptions.TryGetValue(GetSelectedJobPrototype(), out var option))
            return;

        JobPrototypeLabel.Text = option.JobPrototype;
        DepartmentLabel.Text = option.Department;

        if (updateBaseSalary)
            BaseSalarySpinBox.OverrideValue(option.BaseSalary);

        UpdateTotalLabel();
    }

    private bool TrySelectJob(string jobPrototype)
    {
        var index = _jobOptionIds.IndexOf(jobPrototype);
        if (index < 0)
            return false;

        return JobOptionButton.TrySelectId(index);
    }

    private string GetSelectedJobPrototype()
    {
        if (JobOptionButton.ItemCount <= 0 ||
            JobOptionButton.SelectedId < 0 ||
            JobOptionButton.SelectedId >= _jobOptionIds.Count)
            return _lastJobPrototype ?? string.Empty;

        return _jobOptionIds[JobOptionButton.SelectedId];
    }

    private void ClearEditorTracking()
    {
        _lastPopulatedRecord = null;
        _lastJobPrototype = null;
        _lastStatus = null;
        _lastBaseSalary = null;
        _lastAdjustment = null;
    }

    private void UpdateTotalLabel()
    {
        var total = Math.Max(0, BaseSalarySpinBox.Value + AdjustmentSpinBox.Value);
        TotalSalaryLabel.Text = Loc.GetString("forge-payroll-console-total-value", ("amount", total));
    }

    private static string FormatDuration(int seconds)
    {
        var span = TimeSpan.FromSeconds(seconds);
        return span.TotalHours >= 1
            ? $"{(int) span.TotalHours:00}:{span.Minutes:00}:{span.Seconds:00}"
            : $"{span.Minutes:00}:{span.Seconds:00}";
    }

    private static string GetStatusName(ForgePayrollEmploymentStatus status)
    {
        return Loc.GetString($"forge-payroll-status-{status.ToString().ToLowerInvariant()}");
    }
}
