using System.Linq;
using Content.Shared._Forge.Payroll;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.StylesheetHelpers;

namespace Content.Client._Forge.Payroll.UI;

[GenerateTypedNameReferences]
public sealed partial class ForgePayrollConsoleWindow : DefaultWindow
{
    private static readonly Color RootBackground = Color.FromHex("#10141A");
    private static readonly Color PanelBackground = Color.FromHex("#171C24");
    private static readonly Color PanelBackgroundAlt = Color.FromHex("#141922");
    private static readonly Color PanelBorder = Color.FromHex("#344152");
    private static readonly Color InputBackground = Color.FromHex("#0F131A");
    private static readonly Color InputBorder = Color.FromHex("#3F4B60");
    private static readonly Color PrimaryText = Color.FromHex("#ECE6D8");
    private static readonly Color MutedText = Color.FromHex("#A9B0BC");
    private static readonly Color AccentText = Color.FromHex("#E5C07B");
    private static readonly Color MoneyText = Color.FromHex("#9ED59A");
    private static readonly Color FineText = Color.FromHex("#E59A8B");
    private static readonly Color ButtonText = Color.FromHex("#F1EEE6");

    public event Action<NetEntity>? OnRecordSelected;
    public event Action<NetEntity, string, int, int, int, ForgePayrollEmploymentStatus>? OnSavePressed;
    public event Action<NetEntity>? OnPayNowPressed;
    public event Action<NetEntity, int, string>? OnFinePressed;

    private bool _isPopulating;
    private NetEntity? _selected;
    private NetEntity? _lastPopulatedRecord;
    private string? _lastJobPrototype;
    private ForgePayrollEmploymentStatus? _lastStatus;
    private int? _lastBaseSalary;
    private int? _lastAdjustment;
    private int? _lastBankBalance;
    private ForgePayrollConsoleState? _lastState;
    private string _recordFilter = string.Empty;
    private readonly List<string> _jobOptionIds = new();
    private readonly Dictionary<string, ForgePayrollJobOptionState> _jobOptions = new();

    public ForgePayrollConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyVisualTheme();

        RecordsList.OnItemSelected += args =>
        {
            if (_isPopulating || RecordsList[args.ItemIndex].Metadata is not NetEntity employee)
                return;

            _selected = employee;
            OnRecordSelected?.Invoke(employee);
        };

        RecordsList.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                _selected = null;
        };

        BaseSalarySpinBox.IsValid = value => value is >= 0 and <= 250000;
        AdjustmentSpinBox.IsValid = value => value is >= -250000 and <= 250000;
        BankBalanceSpinBox.IsValid = value => value is >= 0 and <= 1000000000;
        FineAmountSpinBox.IsValid = value => value is >= 1 and <= 250000;
        FineReasonLineEdit.IsValid = value => value.Length <= 96;
        CrewSearchLineEdit.IsValid = value => value.Length <= 64;
        CrewSearchLineEdit.OnTextChanged += args =>
        {
            _recordFilter = args.Text.Trim();
            if (_lastState != null)
                PopulateRecords(_lastState);
        };

        foreach (var status in Enum.GetValues<ForgePayrollEmploymentStatus>())
        {
            StatusOptionButton.AddItem(GetStatusName(status), (int) status);
        }

        StatusOptionButton.OnItemSelected += args => StatusOptionButton.SelectId(args.Id);
        JobOptionButton.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            ApplySelectedJobOption();
        };

        BaseSalarySpinBox.ValueChanged += _ => UpdateTotalLabel();
        AdjustmentSpinBox.ValueChanged += _ => UpdateTotalLabel();

        SaveButton.OnPressed += _ =>
        {
            if (_selected is not { } employee)
                return;

            OnSavePressed?.Invoke(
                employee,
                GetSelectedJobPrototype(),
                BaseSalarySpinBox.Value,
                AdjustmentSpinBox.Value,
                BankBalanceSpinBox.Value,
                (ForgePayrollEmploymentStatus) StatusOptionButton.SelectedId);
        };

        PayNowButton.OnPressed += _ =>
        {
            if (_selected is { } employee)
                OnPayNowPressed?.Invoke(employee);
        };

        FineButton.OnPressed += _ =>
        {
            if (_selected is { } employee)
                OnFinePressed?.Invoke(employee, FineAmountSpinBox.Value, FineReasonLineEdit.Text);
        };
    }

    public void UpdateState(ForgePayrollConsoleState state)
    {
        _lastState = state;
        var selectedRecord = _selected is { } selected
            ? state.Records.FirstOrDefault(record => record.Entity == selected)
            : null;

        if (selectedRecord == null && state.Selected is { } stateSelected)
        {
            selectedRecord = state.Records.FirstOrDefault(record => record.Entity == stateSelected);
            _selected = stateSelected;
        }
        else if (selectedRecord == null)
        {
            _selected = null;
        }

        PopulateJobOptions(state.JobOptions);
        PopulateRecords(state);
        PopulateEditor(selectedRecord, state.CanEdit);
    }

    private void PopulateJobOptions(IReadOnlyList<ForgePayrollJobOptionState> jobOptions)
    {
        var selectedJob = GetSelectedJobPrototype();

        _isPopulating = true;
        JobOptionButton.Clear();
        _jobOptionIds.Clear();
        _jobOptions.Clear();

        foreach (var option in jobOptions)
        {
            var id = _jobOptionIds.Count;
            _jobOptionIds.Add(option.JobPrototype);
            _jobOptions[option.JobPrototype] = option;
            JobOptionButton.AddItem(Loc.GetString("forge-payroll-console-job-option",
                ("job", option.JobTitle),
                ("department", option.Department)), id);
        }

        if (!string.IsNullOrWhiteSpace(selectedJob))
            TrySelectJob(selectedJob);

        _isPopulating = false;
    }

    private void PopulateRecords(ForgePayrollConsoleState state)
    {
        _isPopulating = true;
        RecordsList.Clear();
        RecordsList.ClearSelected();
        var records = state.Records
            .Where(RecordMatchesFilter)
            .ToList();

        CrewCountLabel.Text = records.Count == state.Records.Count
            ? Loc.GetString("forge-payroll-console-crew-count", ("count", state.Records.Count))
            : Loc.GetString(
                "forge-payroll-console-crew-count-filtered",
                ("visible", records.Count),
                ("count", state.Records.Count));

        foreach (var record in records)
        {
            var item = RecordsList.AddItem(Loc.GetString("forge-payroll-console-record-entry-compact",
                ("name", record.EmployeeName),
                ("job", record.JobTitle),
                ("salary", record.TotalSalary),
                ("status", GetStatusName(record.Status))));
            item.Metadata = record.Entity;
            item.Selected = record.Entity == _selected;
            item.TooltipText = Loc.GetString("forge-payroll-console-record-entry",
                ("name", record.EmployeeName),
                ("job", record.JobTitle),
                ("salary", record.TotalSalary),
                ("status", GetStatusName(record.Status)));
        }

        _isPopulating = false;
    }

    private void PopulateEditor(ForgePayrollRecordState? record, bool canEdit)
    {
        var hasRecord = record != null;
        var selectedChanged = record?.Entity != _lastPopulatedRecord;

        SelectionLabel.Text = hasRecord
            ? Loc.GetString("forge-payroll-console-selected")
            : Loc.GetString("forge-payroll-console-no-selection");

        EmployeeNameLabel.Text = record?.EmployeeName ?? string.Empty;

        if (record == null)
        {
            JobPrototypeLabel.Text = string.Empty;
            DepartmentLabel.Text = string.Empty;
            JobOptionButton.TrySelect(0);
            StatusOptionButton.TrySelectId((int) ForgePayrollEmploymentStatus.Working);
            BaseSalarySpinBox.OverrideValue(0);
            AdjustmentSpinBox.OverrideValue(0);
            BankBalanceSpinBox.OverrideValue(0);
            FineAmountSpinBox.OverrideValue(1);
            FineReasonLineEdit.Text = string.Empty;
            ClearEditorTracking();
        }
        else
        {
            var jobDirty = _lastJobPrototype != null && GetSelectedJobPrototype() != _lastJobPrototype;
            var statusDirty = _lastStatus != null && StatusOptionButton.SelectedId != (int) _lastStatus.Value;
            var baseSalaryDirty = _lastBaseSalary != null && BaseSalarySpinBox.Value != _lastBaseSalary.Value;
            var adjustmentDirty = _lastAdjustment != null && AdjustmentSpinBox.Value != _lastAdjustment.Value;
            var bankBalanceDirty = _lastBankBalance != null && BankBalanceSpinBox.Value != _lastBankBalance.Value;

            if (selectedChanged || !jobDirty)
                TrySelectJob(record.JobPrototype);

            if (selectedChanged || !statusDirty)
                StatusOptionButton.TrySelectId((int) record.Status);

            if (selectedChanged || !baseSalaryDirty)
                BaseSalarySpinBox.OverrideValue(record.BaseSalary);

            if (selectedChanged || !adjustmentDirty)
                AdjustmentSpinBox.OverrideValue(record.Adjustment);

            if (selectedChanged || !bankBalanceDirty)
                BankBalanceSpinBox.OverrideValue(record.BankBalance);

            if (selectedChanged)
            {
                FineAmountSpinBox.OverrideValue(100);
                FineReasonLineEdit.Text = string.Empty;
            }

            _lastPopulatedRecord = record.Entity;
            _lastJobPrototype = record.JobPrototype;
            _lastStatus = record.Status;
            _lastBaseSalary = record.BaseSalary;
            _lastAdjustment = record.Adjustment;
            _lastBankBalance = record.BankBalance;

            if (!jobDirty)
            {
                JobPrototypeLabel.Text = record.JobPrototype;
                DepartmentLabel.Text = record.Department;
            }
            else
            {
                ApplySelectedJobOption(false);
            }
        }

        NextPayLabel.Text = record == null
            ? string.Empty
            : FormatDuration(record.SecondsToNextPay);
        LastPayLabel.Text = record == null
            ? string.Empty
            : Loc.GetString("forge-payroll-console-last-pay-value", ("amount", record.LastPaidAmount));
        var fineReason = record == null || string.IsNullOrWhiteSpace(record.LastFineReason)
            ? Loc.GetString("forge-payroll-console-fine-no-reason")
            : record.LastFineReason;
        LastFineLabel.Text = record == null || record.LastFineAmount <= 0
            ? Loc.GetString("forge-payroll-console-no-fine")
            : Loc.GetString("forge-payroll-console-last-fine-value",
                ("amount", record.LastFineAmount),
                ("reason", fineReason));
        OutstandingFineLabel.Text = record == null
            ? string.Empty
            : Loc.GetString("forge-payroll-console-total-value", ("amount", record.OutstandingFineAmount));

        EmployeeNameLabel.FontColorOverride = hasRecord ? PrimaryText : MutedText;
        JobPrototypeLabel.FontColorOverride = hasRecord ? MutedText : MutedText;
        DepartmentLabel.FontColorOverride = hasRecord ? AccentText : MutedText;
        NextPayLabel.FontColorOverride = hasRecord ? PrimaryText : MutedText;
        LastPayLabel.FontColorOverride = record != null && record.LastPaidAmount > 0 ? MoneyText : MutedText;
        LastFineLabel.FontColorOverride = record != null && record.LastFineAmount > 0 ? FineText : MutedText;
        OutstandingFineLabel.FontColorOverride = record != null && record.OutstandingFineAmount > 0 ? FineText : MutedText;

        JobOptionButton.Disabled = !hasRecord || !canEdit || JobOptionButton.ItemCount <= 0;
        StatusOptionButton.Disabled = !hasRecord || !canEdit;
        BaseSalarySpinBox.LineEditDisabled = !hasRecord || !canEdit;
        BaseSalarySpinBox.SetButtonDisabled(!hasRecord || !canEdit);
        AdjustmentSpinBox.LineEditDisabled = !hasRecord || !canEdit;
        AdjustmentSpinBox.SetButtonDisabled(!hasRecord || !canEdit);
        BankBalanceSpinBox.LineEditDisabled = !hasRecord || !canEdit;
        BankBalanceSpinBox.SetButtonDisabled(!hasRecord || !canEdit);
        FineAmountSpinBox.LineEditDisabled = !hasRecord || !canEdit;
        FineAmountSpinBox.SetButtonDisabled(!hasRecord || !canEdit);
        FineReasonLineEdit.Editable = hasRecord && canEdit;
        SaveButton.Disabled = !hasRecord || !canEdit;
        FineButton.Disabled = !hasRecord || !canEdit;
        PayNowButton.Disabled = !hasRecord || !canEdit || record?.TotalSalary <= 0 ||
                                record?.Status != ForgePayrollEmploymentStatus.Working;

        UpdateTotalLabel();
    }

    private bool RecordMatchesFilter(ForgePayrollRecordState record)
    {
        if (string.IsNullOrWhiteSpace(_recordFilter))
            return true;

        return record.EmployeeName.Contains(_recordFilter, StringComparison.CurrentCultureIgnoreCase) ||
               record.JobTitle.Contains(_recordFilter, StringComparison.CurrentCultureIgnoreCase) ||
               record.JobPrototype.Contains(_recordFilter, StringComparison.CurrentCultureIgnoreCase) ||
               record.Department.Contains(_recordFilter, StringComparison.CurrentCultureIgnoreCase) ||
               record.BankBalance.ToString().Contains(_recordFilter, StringComparison.CurrentCultureIgnoreCase) ||
               GetStatusName(record.Status).Contains(_recordFilter, StringComparison.CurrentCultureIgnoreCase);
    }

    private void ApplySelectedJobOption(bool updateBaseSalary = true)
    {
        if (_isPopulating || !_jobOptions.TryGetValue(GetSelectedJobPrototype(), out var option))
            return;

        JobPrototypeLabel.Text = option.JobPrototype;
        DepartmentLabel.Text = option.Department;

        if (updateBaseSalary)
            BaseSalarySpinBox.OverrideValue(option.BaseSalary);

        UpdateTotalLabel();
    }

    private bool TrySelectJob(string jobPrototype)
    {
        var index = _jobOptionIds.IndexOf(jobPrototype);
        if (index < 0)
            return false;

        return JobOptionButton.TrySelectId(index);
    }

    private string GetSelectedJobPrototype()
    {
        if (JobOptionButton.ItemCount <= 0 ||
            JobOptionButton.SelectedId < 0 ||
            JobOptionButton.SelectedId >= _jobOptionIds.Count)
            return _lastJobPrototype ?? string.Empty;

        return _jobOptionIds[JobOptionButton.SelectedId];
    }

    private void ClearEditorTracking()
    {
        _lastPopulatedRecord = null;
        _lastJobPrototype = null;
        _lastStatus = null;
        _lastBaseSalary = null;
        _lastAdjustment = null;
        _lastBankBalance = null;
    }

    private void UpdateTotalLabel()
    {
        var total = Math.Max(0, BaseSalarySpinBox.Value + AdjustmentSpinBox.Value);
        TotalSalaryLabel.Text = Loc.GetString("forge-payroll-console-total-value", ("amount", total));
        TotalSalaryLabel.FontColorOverride = total > 0 ? MoneyText : MutedText;
    }

    private void ApplyVisualTheme()
    {
        RootFrame.PanelOverride = BuildPanelStyle(RootBackground, Color.FromHex("#202936"), 0);
        RosterPanel.PanelOverride = BuildPanelStyle(PanelBackground, PanelBorder);
        RecordsFrame.PanelOverride = BuildPanelStyle(InputBackground, Color.FromHex("#27313F"), 4);
        DetailsPanel.PanelOverride = BuildPanelStyle(PanelBackground, PanelBorder);
        PayrollPanel.PanelOverride = BuildPanelStyle(PanelBackgroundAlt, Color.FromHex("#3C5148"));
        FinePanel.PanelOverride = BuildPanelStyle(PanelBackgroundAlt, Color.FromHex("#563D3D"));
        ActionsPanel.PanelOverride = BuildPanelStyle(Color.FromHex("#131820"), PanelBorder);

        RecordsList.ItemSeparation = 4;
        RecordsList.Stylesheet = new Stylesheet(new StyleRule[]
        {
            Element<VScrollBar>()
                .Prop(ScrollBar.StylePropertyGrabber, BuildScrollGrabberStyle(Color.FromHex("#3A4656"))),
            Element<VScrollBar>().Pseudo(ScrollBar.StylePseudoClassHover)
                .Prop(ScrollBar.StylePropertyGrabber, BuildScrollGrabberStyle(Color.FromHex("#4C5D71"))),
            Element<VScrollBar>().Pseudo(ScrollBar.StylePseudoClassGrabbed)
                .Prop(ScrollBar.StylePropertyGrabber, BuildScrollGrabberStyle(Color.FromHex("#6E8FC0"))),
            Element<ItemList>()
                .Prop("font-color", PrimaryText)
                .Prop(ItemList.StylePropertyBackground, BuildListBackgroundStyle())
                .Prop(ItemList.StylePropertyItemBackground, BuildListItemStyle(Color.FromHex("#171D27"), Color.FromHex("#242D3A")))
                .Prop(ItemList.StylePropertySelectedItemBackground, BuildListItemStyle(Color.FromHex("#29364A"), Color.FromHex("#C39B54")))
                .Prop(ItemList.StylePropertyDisabledItemBackground, BuildListItemStyle(Color.FromHex("#11151C"), Color.FromHex("#222832")))
        });

        StyleLineEdit(CrewSearchLineEdit);
        StyleLineEdit(FineReasonLineEdit);
        StyleSpinBox(BaseSalarySpinBox);
        StyleSpinBox(AdjustmentSpinBox);
        StyleSpinBox(BankBalanceSpinBox);
        StyleSpinBox(FineAmountSpinBox);
        StyleOptionButton(JobOptionButton);
        StyleOptionButton(StatusOptionButton);

        SelectionLabel.FontColorOverride = AccentText;
        EmployeeNameLabel.FontColorOverride = MutedText;
        CrewCountLabel.FontColorOverride = AccentText;
        LastPayLabel.FontColorOverride = MutedText;
        LastFineLabel.FontColorOverride = MutedText;
        OutstandingFineLabel.FontColorOverride = MutedText;

        StyleButton(SaveButton, Color.FromHex("#243652"), Color.FromHex("#6E8FC0"));
        StyleButton(PayNowButton, Color.FromHex("#1F3A2B"), Color.FromHex("#68A46E"));
        StyleButton(FineButton, Color.FromHex("#462525"), Color.FromHex("#B15D55"));
    }

    private static void StyleLineEdit(LineEdit lineEdit)
    {
        lineEdit.StyleBoxOverride = BuildInputStyle();
        lineEdit.ModulateSelfOverride = PrimaryText;
    }

    private static void StyleSpinBox(SpinBox spinBox)
    {
        spinBox.LineEditControl.StyleBoxOverride = BuildInputStyle();
        spinBox.LineEditControl.ModulateSelfOverride = PrimaryText;
    }

    private static void StyleOptionButton(OptionButton button)
    {
        button.StyleBoxOverride = BuildInputStyle();
        button.ModulateSelfOverride = PrimaryText;
    }

    private static void StyleButton(Button button, Color background, Color border)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5
        };
        button.ModulateSelfOverride = ButtonText;
    }

    private static StyleBoxFlat BuildInputStyle() =>
        new()
        {
            BackgroundColor = InputBackground,
            BorderColor = InputBorder,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 7,
            ContentMarginRightOverride = 7,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4
        };

    private static StyleBoxFlat BuildPanelStyle(Color background, Color border, int margin = 8) =>
        new()
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1),
            ContentMarginLeftOverride = margin,
            ContentMarginRightOverride = margin,
            ContentMarginTopOverride = margin,
            ContentMarginBottomOverride = margin
        };

    private static StyleBoxFlat BuildListBackgroundStyle() =>
        new()
        {
            BackgroundColor = InputBackground,
            BorderColor = Color.FromHex("#00000000"),
            BorderThickness = new(0),
            ContentMarginLeftOverride = 2,
            ContentMarginRightOverride = 2,
            ContentMarginTopOverride = 2,
            ContentMarginBottomOverride = 2
        };

    private static StyleBoxFlat BuildScrollGrabberStyle(Color color) =>
        new()
        {
            BackgroundColor = color,
            BorderColor = Color.FromHex("#00000000"),
            BorderThickness = new(0),
            ContentMarginLeftOverride = 2,
            ContentMarginRightOverride = 2
        };

    private static StyleBoxFlat BuildListItemStyle(Color background, Color border) =>
        new()
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 7,
            ContentMarginRightOverride = 7,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5
        };

    private static string FormatDuration(int seconds)
    {
        var span = TimeSpan.FromSeconds(seconds);
        return span.TotalHours >= 1
            ? $"{(int) span.TotalHours:00}:{span.Minutes:00}:{span.Seconds:00}"
            : $"{span.Minutes:00}:{span.Seconds:00}";
    }

    private static string GetStatusName(ForgePayrollEmploymentStatus status)
    {
        return Loc.GetString($"forge-payroll-status-{status.ToString().ToLowerInvariant()}");
    }
}
